### ISSUE TITLE
[Bug]: Cookie failure after changing the password causes 403 logout

### ISSUE THREAD

**Issue by Bidaya0** [HXSecurity/DongTai-webapi#315]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/HXSecurity/DongTai/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/HXSecurity/DongTai/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/HXSecurity/DongTai/issues/new/choose) without success.

### Version

1.1.3

### Installation Type

Official SaaS Service

### Service Name

DongTai-WebAPI

### Describe the details of the bug and the steps to reproduce it

1. change the password
2. change success
3. redriect to default page
4. 403

**Comment by liao545** [comment]
修改默认密码，提交后返回登陆页面。尝试修改后的密码登录，发现登陆失败。使用默认密码登录发现登陆成功。尝试了好几次修改密码，都是返回登录界面但是修改不成功。直到半小时后再次尝试发现修改成功。

**Comment by Bidaya0** [comment]
> 修改默认密码，提交后返回登陆页面。尝试修改后的密码登录，发现登陆失败。使用默认密码登录发现登陆成功。尝试了好几次修改密码，都是返回登录界面但是修改不成功。直到半小时后再次尝试发现修改成功。

是本地部署还是SAAS，能提供详细的复现步骤吗？包括截图和浏览器日志

**Comment by liao545** [comment]
是官方saas，复现尝试修改密码不就行了。截图没有。浏览器chrome

**Comment by liao545** [comment]
后面我修改成功了，我都不知道算不算bug

**Comment by liao545** [comment]
后来我修改成功了，我都不知道算不算bug

**Comment by Bidaya0** [comment]
> 后面我修改成功了，我都不知道算不算bug

这边复现不出来

**Comment by liao545** [comment]
等会我试试看看行不行

**Comment by liao545** [comment]
我测试出来了，我录了两个视频，怎么发给你

**Comment by liao545** [comment]
我录了视频，怎么发送给你

**Comment by liao545** [comment]
我先把视频发给洞态小助手，叫他发给你

**Comment by Bidaya0** [comment]
> 我先把视频发给洞态小助手，叫他发给你

排查好了，您用的那个iast.huoxian.cn对应的服务还没有升级到最新版，正在升级。
这边如果网络没有问题的话建议您使用iast.io

**Comment by liao545** [comment]
> > 我先把视频告诉你洞态小助手，叫他说你
> 
> 排查好了，你用的那个iast.huxian.cn的服务还没有到最新版本，正在升级。 如果网络没有问题的话建议你使用iast.io

好的
